[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  PUBLIC_SUPABASE_URL=https://uhbcqofxiltkapbbonoj.supabase.co/rest/v1/
  PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

